backend/api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from . import views

router = DefaultRouter()
router.register(r'main-messages', views.MainMessageViewSet)
router.register(r'cart', views.CartViewSet, basename='cart')
router.register(r'orders', views.OrderViewSet, basename='orders')

urlpatterns = [
    path('profile/<int:chat_id>/', views.ProfileDetailView.as_view(), name='profile-detail'),
    path('profile/update/', views.ProfileUpdateAPIView.as_view(), name='profile-update'),
    path('profile/track/', views.TrackProductAPIView.as_view(), name='profile-track'),
    path('catalog/', views.CategoryListView.as_view(), name='category-catalog'),
    path('category/<int:pk>/', views.CategoryDetailView.as_view(), name='category-detail'),
    path('products/', views.ProductListView.as_view(), name='products-catalog'),
    path('product/<int:pk>/', views.ProductDetailView.as_view(), name='product-detail'),
    path('', include(router.urls)),
]

backend/django_telegram_bot/urls.py
import os

from django.contrib import admin
from django.conf.urls import static
from django.urls import path, include, re_path
from django_telegram_bot import settings
from shop.views import ImportGoodsView, ImportCategory1CView, ImportProducts1CView, RemoveDuplicates, \
    RemoveNoRefKey, ImportImages1CView, ImportPrices1CView, ImportRests1CView, ProductsCheckList, MarkProductsSale, \
    PhotoCheckList
from django.views.static import serve as mediaserve
from django.views.generic import TemplateView

from shop.telegram.bot import webhook
from django.conf import settings
from api.views import set_csrf_token

urlpatterns = [
    path(settings.BOT_TOKEN + '/', webhook, name='webhook'),
    path('manager/', include('shop.urls')),
    path('api/', include('api.urls')),
    re_path(r'^assets/(?P<path>.*)$', mediaserve, {'document_root': os.path.join(settings.BASE_DIR, 'frontend/dist/assets')}),

    path('admin/import_goods/', ImportGoodsView.as_view(), name='admin_import_goods'),
    path('admin/load_from_1c', ImportCategory1CView.as_view(), name='load_from_1c'),
    path('admin/load_category_from_1c', ImportCategory1CView.as_view(), name='load_category_from_1c'),
    path('admin/load_products_from_1c', ImportProducts1CView.as_view(), name='load_products_from_1c'),
    path('admin/load_prices_from_1c', ImportPrices1CView.as_view(), name='load_prices_from_1c'),
    path('admin/load_rests_from_1c', ImportRests1CView.as_view(), name='load_rests_from_1c'),
    path('admin/load_images_from_1c', ImportImages1CView.as_view(), name='load_images_from_1c'),
    path('admin/mark_sale', MarkProductsSale.as_view(), name='mark_sale'),
    path('admin/remove_duplicates', RemoveDuplicates.as_view(), name='remove_duplicates'),
    path('admin/remove_no_ref_key', RemoveNoRefKey.as_view(), name='remove_no_ref_key'),
    path('admin/products_checklist', ProductsCheckList.as_view(), name='products_checklist'),
    path('admin/photo_checklist', PhotoCheckList.as_view(), name='photo_checklist'),
    path('admin/', admin.site.urls, name='admin'),

    path('set-csrf-token/', set_csrf_token, name='set-csrf-token'),
    path('__debug__/', include('debug_toolbar.urls')),
    path('', include('users.urls')),
]

# 1. СНАЧАЛА добавляем статику и медиа (обязательно ДО re_path)
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [path('__debug__/', include(debug_toolbar.urls))] + urlpatterns
    urlpatterns += static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += [
        re_path(f'^{settings.MEDIA_URL.lstrip("/")}(?P<path>.*)$',
            mediaserve, {'document_root': settings.MEDIA_ROOT}),
        re_path(f'^{settings.STATIC_URL.lstrip("/")}(?P<path>.*)$',
            mediaserve, {'document_root': settings.STATIC_ROOT}),
    ]

# 2. И в самом КОНЦЕ — ловушка для Vue (обрабатывает всё остальное)
urlpatterns += [
    re_path(r'^.*$', TemplateView.as_view(template_name="index.html"), name='home'),
]

backend/users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('user/', views.user, name='user_me'),  # Для получения своего профиля через TWA
    path('user/<int:pk>/', views.user, name='user_detail'),  # Для получения по ID

    path('set-csrf-token/', views.set_csrf_token, name='set_csrf_token'),
    path('login/', views.login_user, name='login_user'),
    path('logout/', views.logout_view, name='logout'),

    path('catalog/', views.catalog, name='products_catalog'),
    path('profile/', views.profile, name='user_profile'),
    path('user_edit/', views.user_edit, name='user_edit'),
]

backend/users/models.py
import decimal

from django.contrib.auth.models import User
from django.db import models

from shop.models import Product, Shop, SALE_TYPES

DISCUSSION_STATUS = (
    ('messaging', 'Принимаем сообщения пользователя'),
    ('phone_main', 'Запросить телефон'),
    ('phone', 'Запросить телефон из корзины'),
    ('phone_profile', 'Именить телефон в профиле'),
    ('first_name', 'Именить имя в профиле'),
    ('last_name', 'Именить фамилию в профиле'),
    ('address', 'Именить адрес магазина в профиле'),
    ('offer_address', 'Именить адрес доставки в профиле'),
)

ORDER_STATUS = (
    ('0', 'Заявка обрабатывается'),
    ('1', 'Ожидается оплата'),
    ('2', 'Сборка заказа'),
    ('3', 'Доставка'),
    ('4', 'Ожидает в пункте выдачи'),
    ('5', 'Получен'),
    ('6', 'Отменен'),
    ('7', 'Предзаказ')
)
PAYMENT = (
    ('0', 'Карта'),
    ('1', 'QR код'),
    ('2', 'Перевод'),
)

PREORDER_SELECTOR = (
    ('split', 'Разделить'),
    ('part-order', 'Только в наличии'),
    ('part-preorder', 'Только в предзаказ'),
    ('preorder', 'Все в предзаказ')
)


class Profile(models.Model):
    date = models.DateTimeField(verbose_name='Дата регистрации', auto_now_add=True)
    discussion_status = models.CharField(max_length=50, verbose_name='Ожидаемое действие от пользователя',
                                         choices=DISCUSSION_STATUS, default='messaging')
    telegram_name = models.CharField(verbose_name='Ник пользователя в Телеграм', max_length=50, blank=True, null=True)
    first_name = models.CharField(verbose_name='Имя пользователя', max_length=150, blank=True, null=True)
    last_name = models.CharField(verbose_name='Фамилия пользователя', max_length=150, blank=True, null=True)
    phone = models.CharField(verbose_name='Номер телефона', max_length=20, blank=True, null=True)
    chat_id = models.BigIntegerField(verbose_name='ИД чата пользователя', db_index=True, unique=True)
    cart_message_id = models.IntegerField(verbose_name='ИД сообщения корзины', blank=True, null=True)
    discount = models.DecimalField(verbose_name='Коэффициент скидки', max_digits=3, decimal_places=2, default=1)
    delivery = models.BooleanField(verbose_name='Доставка', default=False)
    main_shop = models.ForeignKey(Shop, on_delete=models.DO_NOTHING, verbose_name='Магазин доставки', null=True,
                                  blank=True)
    delivery_street = models.CharField(max_length=200, verbose_name='Улица доставки', blank=True, null=True)
    preorder = models.BooleanField(verbose_name='Показывать товары для предзаказа', default=True)
    preorder_selector = models.CharField(max_length=50, verbose_name='Выбор пользовтеля по корзине с предзаказом',
                                         choices=PREORDER_SELECTOR, default='Разделить')
    track = models.ManyToManyField(Product, verbose_name='Отсеживаемые товары', blank=True)

    def __str__(self):
        return f'{self.chat_id}'

    def __int__(self):
        return self.chat_id

    class Meta:
        db_table = 'profile'
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'


class UserMessage(models.Model):
    date = models.DateTimeField(verbose_name='Дата, время сообщениея', auto_now_add=True)
    user = models.ForeignKey(Profile, on_delete=models.PROTECT, verbose_name='Пользователь')
    manager = models.ForeignKey(User, on_delete=models.PROTECT, verbose_name='Менеждер', blank=True, null=True)
    message = models.CharField(max_length=500, verbose_name='Сообщение')
    checked = models.BooleanField(verbose_name='Прочитано', default=False)
    support_message_id = models.IntegerField(verbose_name='Номер сообщения в канале поддержки', blank=True, null=True)
    manager_signature = models.CharField(max_length=100, verbose_name='Подпись менеджера',
                                         blank=True, null=True)

    def __str__(self):
        return self.user.__str__()

    class Meta:
        db_table = 'user_message'
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'


class OrderStatus(models.Model):
    title = models.CharField(max_length=50, verbose_name='Статус заказа', choices=ORDER_STATUS, blank=False,
                             default='Заявка обрабатывается 📝')

    def __str__(self):
        return self.get_title_display()

    class Meta:
        db_table = 'order_status'
        verbose_name = 'Статус заказа'
        verbose_name_plural = 'Статусы заказа'


class Payment(models.Model):
    title = models.CharField(max_length=50, verbose_name='Виды оплат', choices=PAYMENT, blank=False,
                             default='🎟️ Наличными')

    def __str__(self):
        return self.get_title_display()

    class Meta:
        db_table = 'order_payment'
        verbose_name = 'Вид оплаты'
        verbose_name_plural = 'Виды оплаты'


class Carts(models.Model):
    date = models.DateTimeField(verbose_name='Дата, время сообщениея', auto_now_add=True)
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE, verbose_name='Пользователь')
    product = models.ForeignKey(Product, on_delete=models.DO_NOTHING, verbose_name='Товары')
    amount = models.IntegerField(verbose_name='Количество', default=0)
    price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name='Цена')
    order = models.ForeignKey('Orders', related_name='carts', on_delete=models.DO_NOTHING, verbose_name='Заказ', blank=True, null=True)
    preorder = models.BooleanField(verbose_name='Предзаказ', default=False)
    soft_delete = models.BooleanField(verbose_name='Удалить', default=False)

    def __str__(self):
        return self.profile.telegram_name

    class Meta:
        db_table = 'carts'
        verbose_name = 'Корзина'
        verbose_name_plural = 'Корзины'


class Orders(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE, verbose_name='Пользователь')
    date = models.DateField(auto_now_add=True, verbose_name='Дата заказа')
    delivery_info = models.CharField(max_length=500, verbose_name='Информация о доставке', null=True, blank=True)
    order_price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name='Цена заказа')
    admin_check = models.ForeignKey(User, verbose_name='Заявка принята работником:', on_delete=models.PROTECT,
                                    null=True, blank=True)
    deliver = models.BooleanField(verbose_name='Доставить по адресу', default=False)
    status = models.ForeignKey(OrderStatus, blank=True, on_delete=models.DO_NOTHING, verbose_name='Статус заказа')
    delivery_price = models.IntegerField(verbose_name='Стомость доставки', default=0, blank=True, null=True)
    payment = models.ForeignKey(Payment, on_delete=models.DO_NOTHING, verbose_name='Вид оплаты', blank=True, null=True)
    payment_url = models.URLField(verbose_name='Ссылка на оплату Авангард', blank=True, null=True)
    extra_payment_url = models.URLField(verbose_name='Дополнительная ссылка на оплату Авангард', blank=True, null=True)
    qr_img = models.CharField(max_length=100, verbose_name='QR код для оплаты', blank=True, null=True)
    payed = models.BooleanField(verbose_name='Оплачены товары', default=False)
    payed_delivery = models.BooleanField(verbose_name='Оплачена доставка', default=False)
    tracing_num = models.CharField(max_length=30, verbose_name='Трек номер', null=True, blank=True)
    manager_message_id = models.IntegerField(verbose_name='Номер сообщения в канале менеджеров', default=0, blank=True,
                                             null=True)
    sale_type = models.CharField(max_length=50, verbose_name='Тип скидки', choices=SALE_TYPES, blank=False,
                                 default='no_sale')

    def __str__(self):
        return f'{self.id}'

    def update_order_sum(self, order_carts):
        order_sum = 0
        for item in order_carts:
            item.price = item.product.price
            order_sum += item.amount * item.price
        return order_sum

    def add_product(self, product_id: int, add_amount: int):
        add_product = Product.objects.get(id=product_id)
        Carts.objects.create(profile=self.profile, product=add_product, amount=add_amount, price=add_product.price,
                             order=self)
        order_carts = self.carts.all()
        self.order_price = self.update_order_sum(order_carts)
        self.save()

    def update_order_quantity(self, form: dict, rests_action: str, shop: int):
        """Обновляет количество товара и спысываем со склада"""
        """Приимаем на вход словарь где ключ - ид товара, значение - количество"""
        order_carts = self.carts.all()

        if rests_action == 'add' and not form:
            for item in order_carts.values():
                form[item['id']] = item['amount']

        for cart_id in form:
            cart_item = order_carts.filter(id=cart_id)[0]
            if cart_item:
                amount = decimal.Decimal(form[cart_id])
                if amount > decimal.Decimal(0):
                    cart_item.soft_delete = False
                    cart_item.product.edit_rests(rests_action, shop, cart_item.amount, amount)
                    cart_item.amount = amount
                    cart_item.save()
                elif amount <= decimal.Decimal(0):
                    cart_item.amount = 0
                    cart_item.soft_delete = True
                    cart_item.save()

        self.order_price = self.update_order_sum(order_carts)
        self.save()

    def update_order_status(self, new_status: str):
        """Обновляет статус возвращаем действие для склада"""
        rests_action = 'pass'
        if self.status.title != new_status:
            if new_status in ["0", "6", "7"]:
                rests_action = 'add'
            elif self.status.title in ["0", "7"]:
                rests_action = 'remove'
            self.status = OrderStatus.objects.filter(title=new_status)[0]
            self.save()
        return rests_action

    class Meta:

backend/users/forms.py
from django import forms
from django.contrib.auth.models import User


class CreateUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['email', 'password']

    def save(self, commit=True) -> User:
        user = super().save(commit=False)
        user.username = self.cleaned_data["email"]
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

backend/templates/users/messages_detail.html
{% extends 'base.html' %}

{% block content %}
    <script type="text/javascript">
        function countChar() {
            var count_char = document.getElementById("count_char");
            var count_char_textarea = document.getElementById("count_char_textarea");
            count_char.value = 500 - count_char_textarea.value.length;
        }
    </script>
    <details>
        <summary>-> Показать старые сообщения <-</summary>
        {% for user_message in user_old_messages %}

                <table>

                    <tr>
                    {% if user_message.manager %}
                        <td></td><td>{{ user_message.date }} | {{ user_message.message }} <br> {{ user_message.manager }}</td>
                    {% else %}
                        <td>{{ user_message.date }} | {{ user_message.message }} <br> {{ user_message.user }}</td>
                    {% endif %}
                    </tr>
                </table>

        {% endfor %}
    </details>
    {% for user_message in user_new_messages %}

            <table>

                <tr>
                {% if user_message.manager %}
                    <td></td><td>{{ user_message.date }} | {{ user_message.message }} <br> {{ user_message.manager }}</td>
                {% else %}
                    <td>{{ user_message.date }} | {{ user_message.message }} <br> {{ user_message.user }}</td>
                {% endif %}
                </tr>
            </table>

    {% endfor %}
    <form class="form" action="{% url 'send_message' %}" method="post">
       {% csrf_token %}
        <input hidden type="text" name="chat_id" value="{{ pk }}">
        <div id="count_char_block">
            <p>Осталось символов:<input type="text" id="count_char" value="500" readonly="readonly" /></p>
            <p>Сообщение: <textarea name="message" id="count_char_textarea" style="width: 600px;height: 300px;"
                onchange="countChar()" onkeyup="countChar()" ></textarea></p>
        </div>
        <p>Тихое уведомление: <input name="disable_notification" type="checkbox" checked></p>
        <button type="submit">Отправить</button>
    </form>
    <div><p>Заказы пользователя:</p>
    {% for order_id in user_orders %}
        <p><a href="manager/order/{{ order_id.id }}">Заказ № {{ order_id.id }}</a></p>
    {% endfor %}
    </div>
{% endblock %}

backend/templates/users/messages_list.html
{% extends 'base.html' %}
{% load static %}

{% block extrahead %}<meta http-equiv="refresh" content="60">{% endblock %}
{% block content %}
    <table border="1px">
    <tr>
        <td>Пользователь</td>
        <td>Последнее непрочитанное сообщение</td>
    </tr>
    {% for user in users %}
        <tr>
            <td><a href="{% url 'user_messages_detail' user.user.chat_id  %}">{{ user.user }}</a></td>
            <td><a href="{% url 'user_messages_detail' user.user.chat_id  %}">{{ user.message }}</a></td>
        </tr>
    {% endfor %}
</table>
{% endblock %}

backend/templates/users/orders_detail.html
{% extends 'base.html' %}
{% load static shop_tags %}

{% block extrastyle %}
<link rel="stylesheet" href="{% static 'css/chosen.min.css' %}">
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/chosen.jquery.min.js' %}"></script>

<script>
$(document).ready(function(){
	$('.js-chosen').chosen({
		width: '100%',
		no_results_text: 'Совпадений не найдено',
		placeholder_text_single: 'Добавить товар'
	});
});
</script>
{% endblock %}

{% block content %}

<a href="/manager">Вернуться к заказам</a>
<form action="" method="post" class="mt-4" id="formReview">
    {% csrf_token %}
    <h1>Заказ №{{ order.id }}</h1>
    <p>Дата: {{ order.date }}</p>
    <p>Ник в телеграм: {{ order.profile.telegram_name }}</p>
    <p>ФИО: {{ order.profile.first_name }} {{ order.profile.last_name }}</p>
    <p>Номер телефона: {{ order.profile.phone }}</p>
    <p>Доставка: {% if order.deliver %}
                да
            {% else %}
                нет
            {% endif %}
    </p>
    <div>Адрес: {{ order.delivery_info }} | Изменить адрес: <input type="text" name="delivery_info" value="{{ order.delivery_info }}"></div>

    <div>Статус:
        <select name="new_status">
            {% for status in order_statuses %}
                <option
                        {% if status == order.status %} selected {% endif %}
                        value="{{ status.title }}">{{ status }}</option>
            {% endfor %}
        </select>
    </div>
    <div>Магазин списания/возврата:
        <select name="shop">
            {% for shop in shops %}
                <option
                        {% if shop == order.profile.main_shop %} selected {% endif %}

                        value="{{ shop.id }}">{{ shop }}</option>
            {% endfor %}
        </select>
    </div>
    <div>Скидка:
        <select name="new_sale_type" {% if order.status.title not in status_reduction_fields  %} disabled {% endif %}>
            {% for sale_type, sale_name in sale_types %}
            <option
                    {% if sale_type == order.sale_type %} selected {% endif %}
                    value="{{ sale_type }}">{{ sale_name }}
            </option>
            {% endfor %}
        </select>
    </div>
    <table border="1px">
        <tr>
            <td>Название</td>
            <td>Количество</td>
            {% for shop in shops %}
                <td {% if order.profile.main_shop == shop %} bgcolor="green" {% endif %}> {{ shop }}</td>
            {% endfor %}
            <td>Стоимость за шт.</td>
            <td><b>Сумма без скидки</b></td>
        </tr>
        {% for product in products %}
        <tr>
            <td {% if product.soft_delete %} bgcolor="red" {% endif %}>
                {{ product.product.name }} </td>
            <td> <input
                    {% if order.status.title not in status_reduction_fields  %} disabled {% endif %}
                        name="{{ product.id }}" id="contactparent" value="{% formatted_float product.amount %} "></td>
            {% for rest in product.product.rests_set.all %}
                <td {% if product.amount > rest.amount %} bgcolor="yellow" {% endif %}>
                    {% formatted_float rest.amount %} шт.</td>
            {% endfor %}
            {% if product.preorder %}
                <td> {% formatted_float product.product.price %} р.</td>
                <td> <b>{% get_sum product.amount product.product.price %} р.</b></td>
            {% else %}
                <td> {% formatted_float product.price %} р.</td>
                <td> <b>{% get_sum product.amount product.price %} р.</b></td>
            {% endif %}
        </tr>
        {% endfor %}
        {% if order.status.title in status_reduction_fields %}
            <tr>
                <td>
                    <select class="js-chosen" name="add_product" placeholder="Добавить товар">
                        <option value=""></option>
                        {% for add_product in add_products %}
                            <option value="{{ add_product.product.id }}">{{ add_product }}</option>
                        {% endfor %}
                    </select>
                </td>
                <td>
                    <input name="add_num" type="number">
                </td>
            </tr>
        {% endif %}
        {% if order.deliver %}
            <tr>
                <td colspan="2">
                Стоимость доставки
                <input {% if order.status.title != "0" and order.delivery_price != 0 %} disabled {% endif %}
                    type="number" name="delivery_price" value="{{ order.delivery_price }}">
                </td>
            </tr>
            {% if order.status.title != "0" %}
            <tr>
                <td colspan="2">
                Трек номер
                <input type="text" name="tracing_num" value="{{ order.tracing_num }}">
                </td>
            </tr>
            {% endif %}
        {% endif %}
    </table>
    <button type="submit">Записать</button>
    </form>
    {% if order.sale_type != 'no_sale' %}
        <p>Скидка: {{ full_discount }} р.</p>
        <p>Сумма со скидкой: {{ order_sum }} р.</p>
    {% else %}
        <p>Сумма: {{ order_sum }} р.</p>
    {% endif %}

    <p> {% if not order.admin_check %}
        Обработанна: -
    {% else %}
        Обработанна: {{ order.admin_check.first_name }} {{ order.admin_check.last_name }}
    {% endif %}
    </p>
<br>
<h2>Общение с пользователем</h2>
<a href="{% url 'user_messages_detail' order.profile.chat_id %}">Перейти к сообщениям пользователя</a>
<form class="form" action="{% url 'send_message' %}" method="post">
   {% csrf_token %}
    <input hidden type="text" name="chat_id" value="{{ order.profile.chat_id }}">
    <p>Сообщение: <textarea name="message"></textarea></p>
    <p>Тихое уведомление: <input name="disable_notification" type="checkbox" checked></p>
    <button type="submit">Отправить</button>
</form>
{% endblock %}

backend/templates/users/orders_list.html
{% extends 'base.html' %}
{% load static shop_tags %}

{% block extrahead %}
<meta http-equiv="refresh" content="120">{% endblock %}
{% block content %}
{% if request.user.is_superuser %}
<div class="{{ bot_status_class }}">Статус бота: {{ bot_status_text }}</div>
<p>Пользователей {{ count_users }}, указали номер телефона {{ count_users_phone }}</p>
{% endif %}
{% if new_message %}
{% endif %}

<h1>Список заявок</h1>
<div pading="2px">
    <form name="orders_filter">
        <select name="filter_date_year">
            <option value="">Год (все)</option>
            {% for year in orders_years %}
                <option {% if year.date__year == filter_year %} selected {% endif %} value="{{ year.date__year }}">
                    {{ year.date__year }}
                </option>
            {% endfor %}
        </select>
        <select name="filter_date_month">
            <option value="">Месяц (все)</option>
            {% for month in orders_months %}
                <option {% if month.date__month == filter_month %} selected {% endif %} value="{{ month.date__month }}">
                    {{ month.date__month }}
                </option>
            {% endfor %}
        </select>
        <select name="filter_status">
            <option value="">Статус (все)</option>
            {% for status in order_statuses %}
            <option {% if status.id == filter_status.id %} selected {% endif %}
                    value="{{ status.id }}">{{ status }}
            </option>
            {% endfor %}
        </select>
        <button type="submit">Найти</button>
    </form>

</div>

<table border="1px">
    <tr>
        <td>Дата оформления</td>
        <td>Заказ №</td>
        <td>Статус</td>
        <td>Взял в обработку</td>
        <td>Доставка</td>
        <td>Адрес</td>
        <td>Скидка</td>
        <td>Оплачены товары</td>
        <td>Оплачена доставка</td>
    </tr>
    {% for order in orders %}
    <tr>
        <td>{{ order.date }}</td>
        <td><a href="{% url 'orders_detail' order.id  %}">{{ order.id }}</a></td>
        <td><a href="{% url 'orders_detail' order.id  %}">{{ order.status }}</a></td>
        <td><a href="{% url 'orders_detail' order.id  %}">
            {% if not order.admin_check %}
            -
            {% else %}
            {{ order.admin_check.first_name }}
            {% endif %}
        </a></td>

        <td><a href="{% url 'orders_detail' order.id  %}">
            {% if order.deliver %}
            да
            {% else %}
            нет
            {% endif %}
        </a></td>
        <td><a href="{% url 'orders_detail' order.id  %}">{{ order.delivery_info }}</a></td>
        <td>
            {{ order.get_sale_type_display }}
        </td>
        <td>
            {% if order.payed %} да {% else %} нет {% endif %}
        </td>
        <td>
            {% if order.payed_delivery %} да {% else %} нет {% endif %}
        </td>
    </tr>
    {% endfor %}
</table>
<p>Всего заявок {{ orders_count }} шт.</p>
<p>На сумму {{ price_sum }} р. (средняя стоимость заказа {{ price_avg }} р.)</p>

{% endblock %}

backend/templates/users/send_everyone.html
{% extends 'base.html' %}
{% load shop_tags %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Отправить сообщение ВСЕМ</title>
    </head>
    <body>
    <script type="text/javascript">
        function countChar() {
            var count_char = document.getElementById("count_char");
            var count_char_textarea = document.getElementById("count_char_textarea");
            count_char.value = 500 - count_char_textarea.value.length;
        }
    </script>
    <a href="/manager">Вернуться к заказам</a>
    <form action="" method="post" class="mt-4" id="formReview">
        {% csrf_token %}
        <h1>!Внимание сообщение будет отправленно ВСЕМ пользователям!</h1>
        <div id="count_char_block">
            <p>Осталось символов:<input type="text" id="count_char" value="500" readonly="readonly" /></p>
            <p>Сообщение: <textarea name="message" id="count_char_textarea" style="width: 600px;height: 300px;"
                onchange="countChar()" onkeyup="countChar()" ></textarea></p>
        </div>
        <p>Тихое уведомление: <input name="disable_notification" type="checkbox" checked></p>
        <button type="submit">Записать</button>
    </form>

    </body>
</html>
{% endblock %}

backend/templates/users/send_message.html
{% extends 'base.html' %}
{% load shop_tags %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Отправить сообщение пользователю</title>
    </head>
    <body>
    <a href="/manager">Вернуться к заказам</a>
    <form action="" method="post" class="mt-4" id="formReview">
        {% csrf_token %}
        <p>Ид чата: <input type="text" name="chat_id" value=""></p>
        <p>Сообщение: <textarea name="message"></textarea></p>
        <button type="submit">Записать</button>
    </form>

    </body>
</html>
{% endblock %}