backend/api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from . import views

router = DefaultRouter()
router.register(r'main-messages', views.MainMessageViewSet)
router.register(r'cart', views.CartViewSet, basename='cart')
router.register(r'orders', views.OrderViewSet, basename='orders')

urlpatterns = [
    path('profile/<int:chat_id>/', views.ProfileDetailView.as_view(), name='profile-detail'),
    path('profile/update/', views.ProfileUpdateAPIView.as_view(), name='profile-update'),
    path('profile/track/', views.TrackProductAPIView.as_view(), name='profile-track'),
    path('catalog/', views.CategoryListView.as_view(), name='category-catalog'),
    path('category/<int:pk>/', views.CategoryDetailView.as_view(), name='category-detail'),
    path('products/', views.ProductListView.as_view(), name='products-catalog'),
    path('product/<int:pk>/', views.ProductDetailView.as_view(), name='product-detail'),
    path('', include(router.urls)),
]

backend/django_telegram_bot/urls.py
import os

from django.contrib import admin
from django.conf.urls import static
from django.urls import path, include, re_path
from django_telegram_bot import settings
from shop.views import ImportGoodsView, ImportCategory1CView, ImportProducts1CView, RemoveDuplicates, \
    RemoveNoRefKey, ImportImages1CView, ImportPrices1CView, ImportRests1CView, ProductsCheckList, MarkProductsSale, \
    PhotoCheckList
from django.views.static import serve as mediaserve
from django.views.generic import TemplateView

from shop.telegram.bot import webhook
from django.conf import settings
from api.views import set_csrf_token

urlpatterns = [
    path(settings.BOT_TOKEN + '/', webhook, name='webhook'),
    path('manager/', include('shop.urls')),
    path('api/', include('api.urls')),
    re_path(r'^assets/(?P<path>.*)$', mediaserve, {'document_root': os.path.join(settings.BASE_DIR, 'frontend/dist/assets')}),

    path('admin/import_goods/', ImportGoodsView.as_view(), name='admin_import_goods'),
    path('admin/load_from_1c', ImportCategory1CView.as_view(), name='load_from_1c'),
    path('admin/load_category_from_1c', ImportCategory1CView.as_view(), name='load_category_from_1c'),
    path('admin/load_products_from_1c', ImportProducts1CView.as_view(), name='load_products_from_1c'),
    path('admin/load_prices_from_1c', ImportPrices1CView.as_view(), name='load_prices_from_1c'),
    path('admin/load_rests_from_1c', ImportRests1CView.as_view(), name='load_rests_from_1c'),
    path('admin/load_images_from_1c', ImportImages1CView.as_view(), name='load_images_from_1c'),
    path('admin/mark_sale', MarkProductsSale.as_view(), name='mark_sale'),
    path('admin/remove_duplicates', RemoveDuplicates.as_view(), name='remove_duplicates'),
    path('admin/remove_no_ref_key', RemoveNoRefKey.as_view(), name='remove_no_ref_key'),
    path('admin/products_checklist', ProductsCheckList.as_view(), name='products_checklist'),
    path('admin/photo_checklist', PhotoCheckList.as_view(), name='photo_checklist'),
    path('admin/', admin.site.urls, name='admin'),

    path('set-csrf-token/', set_csrf_token, name='set-csrf-token'),
    path('__debug__/', include('debug_toolbar.urls')),
    path('', include('users.urls')),
]

# 1. СНАЧАЛА добавляем статику и медиа (обязательно ДО re_path)
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [path('__debug__/', include(debug_toolbar.urls))] + urlpatterns
    urlpatterns += static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += [
        re_path(f'^{settings.MEDIA_URL.lstrip("/")}(?P<path>.*)$',
            mediaserve, {'document_root': settings.MEDIA_ROOT}),
        re_path(f'^{settings.STATIC_URL.lstrip("/")}(?P<path>.*)$',
            mediaserve, {'document_root': settings.STATIC_ROOT}),
    ]

# 2. И в самом КОНЦЕ — ловушка для Vue (обрабатывает всё остальное)
urlpatterns += [
    re_path(r'^.*$', TemplateView.as_view(template_name="index.html"), name='home'),
]

backend/users/models.py
import decimal

from django.contrib.auth.models import User
from django.db import models

from shop.models import Product, Shop, SALE_TYPES

DISCUSSION_STATUS = (
    ('messaging', 'Принимаем сообщения пользователя'),
    ('phone_main', 'Запросить телефон'),
    ('phone', 'Запросить телефон из корзины'),
    ('phone_profile', 'Именить телефон в профиле'),
    ('first_name', 'Именить имя в профиле'),
    ('last_name', 'Именить фамилию в профиле'),
    ('address', 'Именить адрес магазина в профиле'),
    ('offer_address', 'Именить адрес доставки в профиле'),
)

ORDER_STATUS = (
    ('0', 'Заявка обрабатывается'),
    ('1', 'Ожидается оплата'),
    ('2', 'Сборка заказа'),
    ('3', 'Доставка'),
    ('4', 'Ожидает в пункте выдачи'),
    ('5', 'Получен'),
    ('6', 'Отменен'),
    ('7', 'Предзаказ')
)
PAYMENT = (
    ('0', 'Карта'),
    ('1', 'QR код'),
    ('2', 'Перевод'),
)

PREORDER_SELECTOR = (
    ('split', 'Разделить'),
    ('part-order', 'Только в наличии'),
    ('part-preorder', 'Только в предзаказ'),
    ('preorder', 'Все в предзаказ')
)


class Profile(models.Model):
    date = models.DateTimeField(verbose_name='Дата регистрации', auto_now_add=True)
    discussion_status = models.CharField(max_length=50, verbose_name='Ожидаемое действие от пользователя',
                                         choices=DISCUSSION_STATUS, default='messaging')
    telegram_name = models.CharField(verbose_name='Ник пользователя в Телеграм', max_length=50, blank=True, null=True)
    first_name = models.CharField(verbose_name='Имя пользователя', max_length=150, blank=True, null=True)
    last_name = models.CharField(verbose_name='Фамилия пользователя', max_length=150, blank=True, null=True)
    phone = models.CharField(verbose_name='Номер телефона', max_length=20, blank=True, null=True)
    chat_id = models.BigIntegerField(verbose_name='ИД чата пользователя', db_index=True, unique=True)
    cart_message_id = models.IntegerField(verbose_name='ИД сообщения корзины', blank=True, null=True)
    discount = models.DecimalField(verbose_name='Коэффициент скидки', max_digits=3, decimal_places=2, default=1)
    delivery = models.BooleanField(verbose_name='Доставка', default=False)
    main_shop = models.ForeignKey(Shop, on_delete=models.DO_NOTHING, verbose_name='Магазин доставки', null=True,
                                  blank=True)
    delivery_street = models.CharField(max_length=200, verbose_name='Улица доставки', blank=True, null=True)
    preorder = models.BooleanField(verbose_name='Показывать товары для предзаказа', default=True)
    preorder_selector = models.CharField(max_length=50, verbose_name='Выбор пользовтеля по корзине с предзаказом',
                                         choices=PREORDER_SELECTOR, default='Разделить')
    track = models.ManyToManyField(Product, verbose_name='Отсеживаемые товары', blank=True)

    def __str__(self):
        return f'{self.chat_id}'

    def __int__(self):
        return self.chat_id

    class Meta:
        db_table = 'profile'
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'


class UserMessage(models.Model):
    date = models.DateTimeField(verbose_name='Дата, время сообщениея', auto_now_add=True)
    user = models.ForeignKey(Profile, on_delete=models.PROTECT, verbose_name='Пользователь')
    manager = models.ForeignKey(User, on_delete=models.PROTECT, verbose_name='Менеждер', blank=True, null=True)
    message = models.CharField(max_length=500, verbose_name='Сообщение')
    checked = models.BooleanField(verbose_name='Прочитано', default=False)
    support_message_id = models.IntegerField(verbose_name='Номер сообщения в канале поддержки', blank=True, null=True)
    manager_signature = models.CharField(max_length=100, verbose_name='Подпись менеджера',
                                         blank=True, null=True)

    def __str__(self):
        return self.user.__str__()

    class Meta:
        db_table = 'user_message'
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'


class OrderStatus(models.Model):
    title = models.CharField(max_length=50, verbose_name='Статус заказа', choices=ORDER_STATUS, blank=False,
                             default='Заявка обрабатывается 📝')

    def __str__(self):
        return self.get_title_display()

    class Meta:
        db_table = 'order_status'
        verbose_name = 'Статус заказа'
        verbose_name_plural = 'Статусы заказа'


class Payment(models.Model):
    title = models.CharField(max_length=50, verbose_name='Виды оплат', choices=PAYMENT, blank=False,
                             default='🎟️ Наличными')

    def __str__(self):
        return self.get_title_display()

    class Meta:
        db_table = 'order_payment'
        verbose_name = 'Вид оплаты'
        verbose_name_plural = 'Виды оплаты'


class Carts(models.Model):
    date = models.DateTimeField(verbose_name='Дата, время сообщениея', auto_now_add=True)
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE, verbose_name='Пользователь')
    product = models.ForeignKey(Product, on_delete=models.DO_NOTHING, verbose_name='Товары')
    amount = models.IntegerField(verbose_name='Количество', default=0)
    price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name='Цена')
    order = models.ForeignKey('Orders', related_name='carts', on_delete=models.DO_NOTHING, verbose_name='Заказ', blank=True, null=True)
    preorder = models.BooleanField(verbose_name='Предзаказ', default=False)
    soft_delete = models.BooleanField(verbose_name='Удалить', default=False)

    def __str__(self):
        return self.profile.telegram_name

    class Meta:
        db_table = 'carts'
        verbose_name = 'Корзина'
        verbose_name_plural = 'Корзины'


class Orders(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE, verbose_name='Пользователь')
    date = models.DateField(auto_now_add=True, verbose_name='Дата заказа')
    delivery_info = models.CharField(max_length=500, verbose_name='Информация о доставке', null=True, blank=True)
    order_price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name='Цена заказа')
    admin_check = models.ForeignKey(User, verbose_name='Заявка принята работником:', on_delete=models.PROTECT,
                                    null=True, blank=True)
    deliver = models.BooleanField(verbose_name='Доставить по адресу', default=False)
    status = models.ForeignKey(OrderStatus, blank=True, on_delete=models.DO_NOTHING, verbose_name='Статус заказа')
    delivery_price = models.IntegerField(verbose_name='Стомость доставки', default=0, blank=True, null=True)
    payment = models.ForeignKey(Payment, on_delete=models.DO_NOTHING, verbose_name='Вид оплаты', blank=True, null=True)
    payment_url = models.URLField(verbose_name='Ссылка на оплату Авангард', blank=True, null=True)
    extra_payment_url = models.URLField(verbose_name='Дополнительная ссылка на оплату Авангард', blank=True, null=True)
    qr_img = models.CharField(max_length=100, verbose_name='QR код для оплаты', blank=True, null=True)
    payed = models.BooleanField(verbose_name='Оплачены товары', default=False)
    payed_delivery = models.BooleanField(verbose_name='Оплачена доставка', default=False)
    tracing_num = models.CharField(max_length=30, verbose_name='Трек номер', null=True, blank=True)
    manager_message_id = models.IntegerField(verbose_name='Номер сообщения в канале менеджеров', default=0, blank=True,
                                             null=True)
    sale_type = models.CharField(max_length=50, verbose_name='Тип скидки', choices=SALE_TYPES, blank=False,
                                 default='no_sale')

    def __str__(self):
        return f'{self.id}'

    def update_order_sum(self, order_carts):
        order_sum = 0
        for item in order_carts:
            item.price = item.product.price
            order_sum += item.amount * item.price
        return order_sum

    def add_product(self, product_id: int, add_amount: int):
        add_product = Product.objects.get(id=product_id)
        Carts.objects.create(profile=self.profile, product=add_product, amount=add_amount, price=add_product.price,
                             order=self)
        order_carts = self.carts.all()
        self.order_price = self.update_order_sum(order_carts)
        self.save()

    def update_order_quantity(self, form: dict, rests_action: str, shop: int):
        """Обновляет количество товара и спысываем со склада"""
        """Приимаем на вход словарь где ключ - ид товара, значение - количество"""
        order_carts = self.carts.all()

        if rests_action == 'add' and not form:
            for item in order_carts.values():
                form[item['id']] = item['amount']

        for cart_id in form:
            cart_item = order_carts.filter(id=cart_id)[0]
            if cart_item:
                amount = decimal.Decimal(form[cart_id])
                if amount > decimal.Decimal(0):
                    cart_item.soft_delete = False
                    cart_item.product.edit_rests(rests_action, shop, cart_item.amount, amount)
                    cart_item.amount = amount
                    cart_item.save()
                elif amount <= decimal.Decimal(0):
                    cart_item.amount = 0
                    cart_item.soft_delete = True
                    cart_item.save()

        self.order_price = self.update_order_sum(order_carts)
        self.save()

    def update_order_status(self, new_status: str):
        """Обновляет статус возвращаем действие для склада"""
        rests_action = 'pass'
        if self.status.title != new_status:
            if new_status in ["0", "6", "7"]:
                rests_action = 'add'
            elif self.status.title in ["0", "7"]:
                rests_action = 'remove'
            self.status = OrderStatus.objects.filter(title=new_status)[0]
            self.save()
        return rests_action

    class Meta:

backend/templates/base.html
{% load i18n static %}<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}{% get_current_language_bidi as LANGUAGE_BIDI %}
<html lang="{{ LANGUAGE_CODE|default:" en-us" }}" dir="{{ LANGUAGE_BIDI|yesno:'rtl,ltr,auto' }}">
<head>
    <title>
    {% block title %}
        {% if new_message %}
            Новое сообщение (Ottuda SPB)
        {% else %}
            Ottuda SPB
        {% endif %}
    {% endblock %}
    </title>
    <link rel="stylesheet" type="text/css" href="{% block stylesheet %}{% static "css/base.css" %}{% endblock %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    {% if not is_popup and is_nav_sidebar_enabled %}
    <link rel="stylesheet" type="text/css" href="{% static "css/nav_sidebar.css" %}">
    <script src="{% static 'js/nav_sidebar.js' %}" defer></script>
    {% endif %}
    {% block extrastyle %}{% endblock %}
    {% if LANGUAGE_BIDI %}
    <link rel="stylesheet" type="text/css" href="{% block stylesheet_rtl %}{% static "css/rtl.css" %}{% endblock %}">{% endif %}
    {% block extrahead %}{% endblock %}
    {% block responsive %}
    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static "css/responsive.css" %}">
    {% if LANGUAGE_BIDI %}
    <link rel="stylesheet" type="text/css" href="{% static "css/responsive_rtl.css" %}">{% endif %}
    {% endblock %}
    {% block blockbots %}
    <meta name="robots" content="NONE,NOARCHIVE">
    {% endblock %}
</head>
{% load i18n %}

<body class="{% if is_popup %}popup {% endif %}{% block bodyclass %}{% endblock %}"
      data-admin-utc-offset="{% now " Z" %}">

<!-- Container -->
<div id="container">

    {% if not is_popup %}
    <!-- Header -->
    <div id="header">
        <div id="branding">
            {% block navigation %}
            <nav class="row-block">
                <div>Ottuda SPB</div>
                <div class="menu-item"><a class="menu-link" href="{% url 'orders_list' %}">Список активных заказов</a>
                </div>
                <div class="menu-item"><a class="menu-link" href="{% url 'orders_history' %}">Исторя заказов</a></div>

                {% if new_message %}
                    <div class="menu-item"><u><a class="menu-link_new-message" href="{% url 'user_messages_list' %}" style="color:red">Сообщения пользователей</a></u></div>
                {% else %}
                    <div class="menu-item"><a class="menu-link" href="{% url 'user_messages_list' %}">Сообщения пользователей</a></div>
                {% endif %}

                {% if request.user.is_superuser %}
                    <div class="menu-item"><a class="menu-link" href="{% url 'send_everyone' %}">Отправить сообщение ВСЕМ</a></div>
                    <div class="menu-item"><a class="menu-link" href="/admin">Админка</a></div>
                {% endif %}

            </nav>
            {% endblock %}

        </div>
        {% block usertools %}
        {% if has_permission %}
        <div id="user-tools">
            {% block welcome-msg %}
            {% translate 'Welcome,' %}
            <strong>{% firstof user.get_short_name user.get_username %}</strong>.
            {% endblock %}
            {% block userlinks %}
            {% if site_url %}
            <a href="{{ site_url }}">{% translate 'View site' %}</a> /
            {% endif %}
            {% if user.is_active and user.is_staff %}
            {% url 'django-admindocs-docroot' as docsroot %}
            {% if docsroot %}
            <a href="{{ docsroot }}">{% translate 'Documentation' %}</a> /
            {% endif %}
            {% endif %}
            {% if user.has_usable_password %}
            <a href="{% url 'admin:password_change' %}">{% translate 'Change password' %}</a> /
            {% endif %}
            <a href="{% url 'admin:logout' %}">{% translate 'Log out' %}</a>
            {% endblock %}
        </div>
        {% endif %}
        {% endblock %}
        {% block nav-global %}
        <div class="menu-item">
            <!--Доступ к профилю для авторизованного пользователя-->
            {% if request.user.is_authenticated %}
            <div class="row-block">
                <div class="display_user"> {{ request.user.first_name }} {{ request.user.last_name }}</div>
                <a class="ControlPanel-title" href="{% url 'logout' %}">Выйти</a>
            </div>
            <!-- Вход или регистрация для неавторизованного пользователя-->
            {% else %}
            <div class="row-block">
                <a class="ControlPanel-title" href="{% url 'login' %}">Войти</a>
            </div>
            {% endif %}
        </div>
        {% endblock %}
    </div>
    <!-- END Header -->
    {% block breadcrumbs %}{% endblock %}
    {% endif %}

    <div class="main shifted" id="main">
        {% if not is_popup and is_nav_sidebar_enabled %}
        {% block nav-sidebar %}
        {% include "admin/nav_sidebar.html" %}
        {% endblock %}
        {% endif %}
        <div class="content">
            {% block messages %}
            {% if messages %}
            <ul class="messagelist">{% for message in messages %}
                <li
                        {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message|capfirst }}
                </li>
                {% endfor %}
            </ul>
            {% endif %}
            {% endblock messages %}
            <!-- Content -->
            <div id="content" class="{% block coltype %}colM{% endblock %}">
                {% block pretitle %}{% endblock %}
                {% block content_title %}{% if title %}<h1>{{ title }}</h1>{% endif %}{% endblock %}
                {% block content_subtitle %}{% if subtitle %}<h2>{{ subtitle }}</h2>{% endif %}{% endblock %}
                {% block content %}
                {% block object-tools %}{% endblock %}
                {{ content }}
                {% endblock %}
                {% block sidebar %}{% endblock %}
                <br class="clear">
            </div>
            <!-- END Content -->
            {% block footer %}
            <div id="footer"></div>
            {% endblock %}
        </div>
    </div>
</div>
<!-- END Container -->
</body>
</html>

backend/templates/login.html
{% block content %}
    <center>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Войти</button>
        </form>
    </center>
{% endblock %}